cc_test(
    name = "test_database",
    srcs = ["test_database.cpp"],
    deps = [
        "//:xxsqlite",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_field",
    srcs = ["test_field.cpp"],
    deps = [
        "//:xxsqlite",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_result",
    srcs = ["test_result.cpp"],
    deps = [
        "//:xxsqlite",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_row",
    srcs = ["test_row.cpp"],
    deps = [
        "//:xxsqlite",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_statement",
    srcs = ["test_statement.cpp"],
    deps = [
        "//:xxsqlite",
        "@com_google_googletest//:gtest_main",
    ],
)
